#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2014 uralbash <root@uralbash.ru>
#
# Distributed under terms of the MIT license.

sudo: false
language: python

notifications:
  email: "sacrud@uralbash.ru"
  email: "arkadiy@bk.ru"
  irc:
    channels:
      - "chat.freenode.net#sacrud"
    on_success: change
    on_failure: always

python:
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  include:
    - python: "2.7"
      env: LINK_CHECK=1

install:
  - pip install -r examples/pages/requirements.txt
  - pip install -r requirements-test.txt
  - python setup.py develop
  - if [ -n "$LINK_CHECK" ];then pip install linkchecker requests>=2.2.0; fi

script:
  # Nosetests
  - python setup.py nosetests

  # Styles check
  - if [ -z "$NO_RSTLINT" ]; then ./test.sh; fi

  # BDD
  - cd examples/pages
  - nohup python pyramid_pages_example.py&
  - sleep 5
  - cd ..

  # Link checker
  - if [ -n "$LINK_CHECK" ];then linkchecker http://localhost:6543/ --ignore-url="unquote\(%*" --no-status; fi

after_success:
  - pip install coveralls
  - coveralls

after_failure:
  cat examples/pages/nohup.out
