#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2014 uralbash <root@uralbash.ru>
#
# Distributed under terms of the MIT license.

language: python

notifications:
  email: "sacrud@uralbash.ru"
  email: "arkadiy@bk.ru"
  irc:
    channels:
      - "chat.freenode.net#sacrud"
    on_success: change
    on_failure: always

python:
  - "2.7"

install:
  - pip install nose coverage coveralls
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package pyramid_sacrud_pages --cover-erase --with-doctest

after_success:
  coveralls
